# fly.toml app configuration file generated for nosebook-socket on 2023-05-23T21:13:14+06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "nosebook-socket"
primary_region = "sin"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
